[packages.sia_sdk]
versioned_files = ["sia_sdk/Cargo.toml"]
changelog = "sia_sdk/CHANGELOG.md"

[packages.sia_sdk_derive]
versioned_files = ["sia_derive/Cargo.toml"]
changelog = "sia_derive/CHANGELOG.md"

[packages.indexd]
versioned_files = ["indexd/Cargo.toml"]
changelog = "indexd/CHANGELOG.md"

[packages.indexd_ffi]
versioned_files = ["indexd_ffi/Cargo.toml"]
changelog = "indexd_ffi/CHANGELOG.md"

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"

[[workflows]]
name = "prepare-release"
ignore_conventional_commits = true

[[workflows.steps]]
type = "PrepareRelease"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"

[github]
owner = "SiaFoundation"
repo = "sia-sdk-rs"
