

# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import asyncio
import platform

# Used for default argument values
_DEFAULT = object() # type: typing.Any


class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_indexd_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_indexd_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_indexd_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError("junk data left in buffer at end of consume_with_stream")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError("junk data left in buffer at end of read_with_stream")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            # XXX TODO: I feel like I should be able to use `struct.pack_into` here but can't figure it out.
            for i, byte in enumerate(struct.pack(format, value)):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write(self, value):
        with self._reserve(len(value)):
            for i, byte in enumerate(value):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiConverterString.lower(repr(e))
class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = itertools.count()

    def insert(self, obj):
        with self._lock:
            handle = next(self._counter)
            self._map[handle] = obj
            return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError("_UniffiHandleMap.get: Invalid handle")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError("_UniffiHandleMap.remove: Invalid handle")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("indexd")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 29
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_indexd_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_indexd_checksum_func_set_log_callback() != 1468:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_indexd_checksum_method_app_connect() != 8583:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_indexd_checksum_method_app_upload() != 21746:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_indexd_checksum_method_chunkedbuffer_close() != 29180:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_indexd_checksum_method_chunkedbuffer_push_chunk() != 15793:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_indexd_checksum_method_logger_debug() != 6094:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_indexd_checksum_method_logger_info() != 35244:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_indexd_checksum_method_logger_warn() != 54856:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_indexd_checksum_method_logger_error() != 36167:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_indexd_checksum_method_upload_finish() != 21023:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_indexd_checksum_method_upload_write() != 12446:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_indexd_checksum_constructor_app_new() != 12493:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_indexd_checksum_constructor_chunkedbuffer_new() != 47497:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,ctypes.c_int8,
)
_UNIFFI_FOREIGN_FUTURE_FREE = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
_UNIFFI_CALLBACK_INTERFACE_FREE = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
class _UniffiForeignFuture(ctypes.Structure):
    _fields_ = [
        ("handle", ctypes.c_uint64),
        ("free", _UNIFFI_FOREIGN_FUTURE_FREE),
    ]
class _UniffiForeignFutureStructU8(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint8),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U8 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU8,
)
class _UniffiForeignFutureStructI8(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int8),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I8 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI8,
)
class _UniffiForeignFutureStructU16(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint16),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U16 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU16,
)
class _UniffiForeignFutureStructI16(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int16),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I16 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI16,
)
class _UniffiForeignFutureStructU32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint32),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU32,
)
class _UniffiForeignFutureStructI32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int32),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI32,
)
class _UniffiForeignFutureStructU64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint64),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU64,
)
class _UniffiForeignFutureStructI64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int64),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI64,
)
class _UniffiForeignFutureStructF32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_float),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_F32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructF32,
)
class _UniffiForeignFutureStructF64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_double),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_F64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructF64,
)
class _UniffiForeignFutureStructPointer(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_void_p),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_POINTER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructPointer,
)
class _UniffiForeignFutureStructRustBuffer(ctypes.Structure):
    _fields_ = [
        ("return_value", _UniffiRustBuffer),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructRustBuffer,
)
class _UniffiForeignFutureStructVoid(ctypes.Structure):
    _fields_ = [
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_VOID = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructVoid,
)
_UNIFFI_CALLBACK_INTERFACE_LOGGER_METHOD0 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiRustBuffer,ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UNIFFI_CALLBACK_INTERFACE_LOGGER_METHOD1 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiRustBuffer,ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UNIFFI_CALLBACK_INTERFACE_LOGGER_METHOD2 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiRustBuffer,ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UNIFFI_CALLBACK_INTERFACE_LOGGER_METHOD3 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiRustBuffer,ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
class _UniffiVTableCallbackInterfaceLogger(ctypes.Structure):
    _fields_ = [
        ("debug", _UNIFFI_CALLBACK_INTERFACE_LOGGER_METHOD0),
        ("info", _UNIFFI_CALLBACK_INTERFACE_LOGGER_METHOD1),
        ("warn", _UNIFFI_CALLBACK_INTERFACE_LOGGER_METHOD2),
        ("error", _UNIFFI_CALLBACK_INTERFACE_LOGGER_METHOD3),
        ("uniffi_free", _UNIFFI_CALLBACK_INTERFACE_FREE),
    ]
_UniffiLib.uniffi_indexd_fn_clone_app.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_indexd_fn_clone_app.restype = ctypes.c_void_p
_UniffiLib.uniffi_indexd_fn_free_app.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_indexd_fn_free_app.restype = None
_UniffiLib.uniffi_indexd_fn_constructor_app_new.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_indexd_fn_constructor_app_new.restype = ctypes.c_void_p
_UniffiLib.uniffi_indexd_fn_method_app_connect.argtypes = (
    ctypes.c_void_p,
)
_UniffiLib.uniffi_indexd_fn_method_app_connect.restype = ctypes.c_uint64
_UniffiLib.uniffi_indexd_fn_method_app_upload.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    ctypes.c_uint8,
    ctypes.c_uint8,
)
_UniffiLib.uniffi_indexd_fn_method_app_upload.restype = ctypes.c_uint64
_UniffiLib.uniffi_indexd_fn_clone_chunkedbuffer.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_indexd_fn_clone_chunkedbuffer.restype = ctypes.c_void_p
_UniffiLib.uniffi_indexd_fn_free_chunkedbuffer.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_indexd_fn_free_chunkedbuffer.restype = None
_UniffiLib.uniffi_indexd_fn_constructor_chunkedbuffer_new.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_indexd_fn_constructor_chunkedbuffer_new.restype = ctypes.c_void_p
_UniffiLib.uniffi_indexd_fn_method_chunkedbuffer_close.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_indexd_fn_method_chunkedbuffer_close.restype = None
_UniffiLib.uniffi_indexd_fn_method_chunkedbuffer_push_chunk.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
)
_UniffiLib.uniffi_indexd_fn_method_chunkedbuffer_push_chunk.restype = ctypes.c_uint64
_UniffiLib.uniffi_indexd_fn_clone_logger.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_indexd_fn_clone_logger.restype = ctypes.c_void_p
_UniffiLib.uniffi_indexd_fn_free_logger.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_indexd_fn_free_logger.restype = None
_UniffiLib.uniffi_indexd_fn_init_callback_vtable_logger.argtypes = (
    ctypes.POINTER(_UniffiVTableCallbackInterfaceLogger),
)
_UniffiLib.uniffi_indexd_fn_init_callback_vtable_logger.restype = None
_UniffiLib.uniffi_indexd_fn_method_logger_debug.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_indexd_fn_method_logger_debug.restype = None
_UniffiLib.uniffi_indexd_fn_method_logger_info.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_indexd_fn_method_logger_info.restype = None
_UniffiLib.uniffi_indexd_fn_method_logger_warn.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_indexd_fn_method_logger_warn.restype = None
_UniffiLib.uniffi_indexd_fn_method_logger_error.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_indexd_fn_method_logger_error.restype = None
_UniffiLib.uniffi_indexd_fn_clone_upload.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_indexd_fn_clone_upload.restype = ctypes.c_void_p
_UniffiLib.uniffi_indexd_fn_free_upload.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_indexd_fn_free_upload.restype = None
_UniffiLib.uniffi_indexd_fn_method_upload_finish.argtypes = (
    ctypes.c_void_p,
)
_UniffiLib.uniffi_indexd_fn_method_upload_finish.restype = ctypes.c_uint64
_UniffiLib.uniffi_indexd_fn_method_upload_write.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
)
_UniffiLib.uniffi_indexd_fn_method_upload_write.restype = ctypes.c_uint64
_UniffiLib.uniffi_indexd_fn_func_set_log_callback.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_indexd_fn_func_set_log_callback.restype = None
_UniffiLib.ffi_indexd_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_indexd_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_indexd_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_indexd_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_indexd_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_indexd_rustbuffer_free.restype = None
_UniffiLib.ffi_indexd_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_indexd_rustbuffer_reserve.restype = _UniffiRustBuffer
_UniffiLib.ffi_indexd_rust_future_poll_u8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_poll_u8.restype = None
_UniffiLib.ffi_indexd_rust_future_cancel_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_cancel_u8.restype = None
_UniffiLib.ffi_indexd_rust_future_free_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_free_u8.restype = None
_UniffiLib.ffi_indexd_rust_future_complete_u8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_indexd_rust_future_complete_u8.restype = ctypes.c_uint8
_UniffiLib.ffi_indexd_rust_future_poll_i8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_poll_i8.restype = None
_UniffiLib.ffi_indexd_rust_future_cancel_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_cancel_i8.restype = None
_UniffiLib.ffi_indexd_rust_future_free_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_free_i8.restype = None
_UniffiLib.ffi_indexd_rust_future_complete_i8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_indexd_rust_future_complete_i8.restype = ctypes.c_int8
_UniffiLib.ffi_indexd_rust_future_poll_u16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_poll_u16.restype = None
_UniffiLib.ffi_indexd_rust_future_cancel_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_cancel_u16.restype = None
_UniffiLib.ffi_indexd_rust_future_free_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_free_u16.restype = None
_UniffiLib.ffi_indexd_rust_future_complete_u16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_indexd_rust_future_complete_u16.restype = ctypes.c_uint16
_UniffiLib.ffi_indexd_rust_future_poll_i16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_poll_i16.restype = None
_UniffiLib.ffi_indexd_rust_future_cancel_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_cancel_i16.restype = None
_UniffiLib.ffi_indexd_rust_future_free_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_free_i16.restype = None
_UniffiLib.ffi_indexd_rust_future_complete_i16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_indexd_rust_future_complete_i16.restype = ctypes.c_int16
_UniffiLib.ffi_indexd_rust_future_poll_u32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_poll_u32.restype = None
_UniffiLib.ffi_indexd_rust_future_cancel_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_cancel_u32.restype = None
_UniffiLib.ffi_indexd_rust_future_free_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_free_u32.restype = None
_UniffiLib.ffi_indexd_rust_future_complete_u32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_indexd_rust_future_complete_u32.restype = ctypes.c_uint32
_UniffiLib.ffi_indexd_rust_future_poll_i32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_poll_i32.restype = None
_UniffiLib.ffi_indexd_rust_future_cancel_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_cancel_i32.restype = None
_UniffiLib.ffi_indexd_rust_future_free_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_free_i32.restype = None
_UniffiLib.ffi_indexd_rust_future_complete_i32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_indexd_rust_future_complete_i32.restype = ctypes.c_int32
_UniffiLib.ffi_indexd_rust_future_poll_u64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_poll_u64.restype = None
_UniffiLib.ffi_indexd_rust_future_cancel_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_cancel_u64.restype = None
_UniffiLib.ffi_indexd_rust_future_free_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_free_u64.restype = None
_UniffiLib.ffi_indexd_rust_future_complete_u64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_indexd_rust_future_complete_u64.restype = ctypes.c_uint64
_UniffiLib.ffi_indexd_rust_future_poll_i64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_poll_i64.restype = None
_UniffiLib.ffi_indexd_rust_future_cancel_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_cancel_i64.restype = None
_UniffiLib.ffi_indexd_rust_future_free_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_free_i64.restype = None
_UniffiLib.ffi_indexd_rust_future_complete_i64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_indexd_rust_future_complete_i64.restype = ctypes.c_int64
_UniffiLib.ffi_indexd_rust_future_poll_f32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_poll_f32.restype = None
_UniffiLib.ffi_indexd_rust_future_cancel_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_cancel_f32.restype = None
_UniffiLib.ffi_indexd_rust_future_free_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_free_f32.restype = None
_UniffiLib.ffi_indexd_rust_future_complete_f32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_indexd_rust_future_complete_f32.restype = ctypes.c_float
_UniffiLib.ffi_indexd_rust_future_poll_f64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_poll_f64.restype = None
_UniffiLib.ffi_indexd_rust_future_cancel_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_cancel_f64.restype = None
_UniffiLib.ffi_indexd_rust_future_free_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_free_f64.restype = None
_UniffiLib.ffi_indexd_rust_future_complete_f64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_indexd_rust_future_complete_f64.restype = ctypes.c_double
_UniffiLib.ffi_indexd_rust_future_poll_pointer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_poll_pointer.restype = None
_UniffiLib.ffi_indexd_rust_future_cancel_pointer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_cancel_pointer.restype = None
_UniffiLib.ffi_indexd_rust_future_free_pointer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_free_pointer.restype = None
_UniffiLib.ffi_indexd_rust_future_complete_pointer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_indexd_rust_future_complete_pointer.restype = ctypes.c_void_p
_UniffiLib.ffi_indexd_rust_future_poll_rust_buffer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_poll_rust_buffer.restype = None
_UniffiLib.ffi_indexd_rust_future_cancel_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_cancel_rust_buffer.restype = None
_UniffiLib.ffi_indexd_rust_future_free_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_free_rust_buffer.restype = None
_UniffiLib.ffi_indexd_rust_future_complete_rust_buffer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_indexd_rust_future_complete_rust_buffer.restype = _UniffiRustBuffer
_UniffiLib.ffi_indexd_rust_future_poll_void.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_poll_void.restype = None
_UniffiLib.ffi_indexd_rust_future_cancel_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_cancel_void.restype = None
_UniffiLib.ffi_indexd_rust_future_free_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_indexd_rust_future_free_void.restype = None
_UniffiLib.ffi_indexd_rust_future_complete_void.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_indexd_rust_future_complete_void.restype = None
_UniffiLib.uniffi_indexd_checksum_func_set_log_callback.argtypes = (
)
_UniffiLib.uniffi_indexd_checksum_func_set_log_callback.restype = ctypes.c_uint16
_UniffiLib.uniffi_indexd_checksum_method_app_connect.argtypes = (
)
_UniffiLib.uniffi_indexd_checksum_method_app_connect.restype = ctypes.c_uint16
_UniffiLib.uniffi_indexd_checksum_method_app_upload.argtypes = (
)
_UniffiLib.uniffi_indexd_checksum_method_app_upload.restype = ctypes.c_uint16
_UniffiLib.uniffi_indexd_checksum_method_chunkedbuffer_close.argtypes = (
)
_UniffiLib.uniffi_indexd_checksum_method_chunkedbuffer_close.restype = ctypes.c_uint16
_UniffiLib.uniffi_indexd_checksum_method_chunkedbuffer_push_chunk.argtypes = (
)
_UniffiLib.uniffi_indexd_checksum_method_chunkedbuffer_push_chunk.restype = ctypes.c_uint16
_UniffiLib.uniffi_indexd_checksum_method_logger_debug.argtypes = (
)
_UniffiLib.uniffi_indexd_checksum_method_logger_debug.restype = ctypes.c_uint16
_UniffiLib.uniffi_indexd_checksum_method_logger_info.argtypes = (
)
_UniffiLib.uniffi_indexd_checksum_method_logger_info.restype = ctypes.c_uint16
_UniffiLib.uniffi_indexd_checksum_method_logger_warn.argtypes = (
)
_UniffiLib.uniffi_indexd_checksum_method_logger_warn.restype = ctypes.c_uint16
_UniffiLib.uniffi_indexd_checksum_method_logger_error.argtypes = (
)
_UniffiLib.uniffi_indexd_checksum_method_logger_error.restype = ctypes.c_uint16
_UniffiLib.uniffi_indexd_checksum_method_upload_finish.argtypes = (
)
_UniffiLib.uniffi_indexd_checksum_method_upload_finish.restype = ctypes.c_uint16
_UniffiLib.uniffi_indexd_checksum_method_upload_write.argtypes = (
)
_UniffiLib.uniffi_indexd_checksum_method_upload_write.restype = ctypes.c_uint16
_UniffiLib.uniffi_indexd_checksum_constructor_app_new.argtypes = (
)
_UniffiLib.uniffi_indexd_checksum_constructor_app_new.restype = ctypes.c_uint16
_UniffiLib.uniffi_indexd_checksum_constructor_chunkedbuffer_new.argtypes = (
)
_UniffiLib.uniffi_indexd_checksum_constructor_chunkedbuffer_new.restype = ctypes.c_uint16
_UniffiLib.ffi_indexd_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_indexd_uniffi_contract_version.restype = ctypes.c_uint32

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)

# Public interface members begin here.
# Magic number for the Rust proxy to call using the same mechanism as every other method,
# to free the callback once it's dropped by Rust.
_UNIFFI_IDX_CALLBACK_FREE = 0
# Return codes for callback calls
_UNIFFI_CALLBACK_SUCCESS = 0
_UNIFFI_CALLBACK_ERROR = 1
_UNIFFI_CALLBACK_UNEXPECTED_ERROR = 2

class _UniffiCallbackInterfaceFfiConverter:
    _handle_map = _UniffiHandleMap()

    @classmethod
    def lift(cls, handle):
        return cls._handle_map.get(handle)

    @classmethod
    def read(cls, buf):
        handle = buf.read_u64()
        cls.lift(handle)

    @classmethod
    def check_lower(cls, cb):
        pass

    @classmethod
    def lower(cls, cb):
        handle = cls._handle_map.insert(cb)
        return handle

    @classmethod
    def write(cls, cb, buf):
        buf.write_u64(cls.lower(cb))

class _UniffiConverterUInt8(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u8"
    VALUE_MIN = 0
    VALUE_MAX = 2**8

    @staticmethod
    def read(buf):
        return buf.read_u8()

    @staticmethod
    def write(value, buf):
        buf.write_u8(value)

class _UniffiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()

class _UniffiConverterBytes(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative byte string length")
        return buf.read(size)

    @staticmethod
    def check_lower(value):
        try:
            memoryview(value)
        except TypeError:
            raise TypeError("a bytes-like object is required, not {!r}".format(type(value).__name__))

    @staticmethod
    def write(value, buf):
        buf.write_i32(len(value))
        buf.write(value)










# BufferError
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class BufferError(Exception):
    pass

_UniffiTempBufferError = BufferError

class BufferError:  # type: ignore
    class Closed(_UniffiTempBufferError):
        def __init__(self):
            pass

        def __repr__(self):
            return "BufferError.Closed({})".format(str(self))
    _UniffiTempBufferError.Closed = Closed # type: ignore

BufferError = _UniffiTempBufferError # type: ignore
del _UniffiTempBufferError


class _UniffiConverterTypeBufferError(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return BufferError.Closed(
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if isinstance(value, BufferError.Closed):
            return

    @staticmethod
    def write(value, buf):
        if isinstance(value, BufferError.Closed):
            buf.write_i32(1)


# Error
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class Error(Exception):
    pass

_UniffiTempError = Error

class Error:  # type: ignore
    class Msg(_UniffiTempError):
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], str):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'str', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "Error.Msg({})".format(str(self))
    _UniffiTempError.Msg = Msg # type: ignore

Error = _UniffiTempError # type: ignore
del _UniffiTempError


class _UniffiConverterTypeError(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return Error.Msg(
                _UniffiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if isinstance(value, Error.Msg):
            _UniffiConverterString.check_lower(value._values[0])
            return

    @staticmethod
    def write(value, buf):
        if isinstance(value, Error.Msg):
            buf.write_i32(1)
            _UniffiConverterString.write(value._values[0], buf)

# objects.
class LoggerProtocol(typing.Protocol):
    def debug(self, msg: "str"):
        raise NotImplementedError
    def info(self, msg: "str"):
        raise NotImplementedError
    def warn(self, msg: "str"):
        raise NotImplementedError
    def error(self, msg: "str"):
        raise NotImplementedError
# Logger is a foreign trait so treated like a callback interface, where the
# primary use-case is the trait being implemented locally.
# It is a base-class local implementations might subclass.


class Logger():
    def debug(self, msg: "str"):
        raise NotImplementedError
    def info(self, msg: "str"):
        raise NotImplementedError
    def warn(self, msg: "str"):
        raise NotImplementedError
    def error(self, msg: "str"):
        raise NotImplementedError
# `LoggerImpl` is the implementation for a Rust implemented version.
class LoggerImpl():
    _pointer: ctypes.c_void_p
    
    def __init__(self, *args, **kwargs):
        raise ValueError("This class has no default constructor")

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_indexd_fn_free_logger, pointer)

    def _uniffi_clone_pointer(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_indexd_fn_clone_logger, self._pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst


    def debug(self, msg: "str") -> None:
        _UniffiConverterString.check_lower(msg)
        
        _uniffi_rust_call(_UniffiLib.uniffi_indexd_fn_method_logger_debug,self._uniffi_clone_pointer(),
        _UniffiConverterString.lower(msg))






    def info(self, msg: "str") -> None:
        _UniffiConverterString.check_lower(msg)
        
        _uniffi_rust_call(_UniffiLib.uniffi_indexd_fn_method_logger_info,self._uniffi_clone_pointer(),
        _UniffiConverterString.lower(msg))






    def warn(self, msg: "str") -> None:
        _UniffiConverterString.check_lower(msg)
        
        _uniffi_rust_call(_UniffiLib.uniffi_indexd_fn_method_logger_warn,self._uniffi_clone_pointer(),
        _UniffiConverterString.lower(msg))






    def error(self, msg: "str") -> None:
        _UniffiConverterString.check_lower(msg)
        
        _uniffi_rust_call(_UniffiLib.uniffi_indexd_fn_method_logger_error,self._uniffi_clone_pointer(),
        _UniffiConverterString.lower(msg))






# Put all the bits inside a class to keep the top-level namespace clean
class _UniffiTraitImplLogger:
    # For each method, generate a callback function to pass to Rust

    @_UNIFFI_CALLBACK_INTERFACE_LOGGER_METHOD0
    def debug(
            uniffi_handle,
            msg,
            uniffi_out_return,
            uniffi_call_status_ptr,
        ):
        uniffi_obj = _UniffiConverterTypeLogger._handle_map.get(uniffi_handle)
        def make_call():
            args = (_UniffiConverterString.lift(msg), )
            method = uniffi_obj.debug
            return method(*args)

        
        write_return_value = lambda v: None
        _uniffi_trait_interface_call(
                uniffi_call_status_ptr.contents,
                make_call,
                write_return_value,
        )

    @_UNIFFI_CALLBACK_INTERFACE_LOGGER_METHOD1
    def info(
            uniffi_handle,
            msg,
            uniffi_out_return,
            uniffi_call_status_ptr,
        ):
        uniffi_obj = _UniffiConverterTypeLogger._handle_map.get(uniffi_handle)
        def make_call():
            args = (_UniffiConverterString.lift(msg), )
            method = uniffi_obj.info
            return method(*args)

        
        write_return_value = lambda v: None
        _uniffi_trait_interface_call(
                uniffi_call_status_ptr.contents,
                make_call,
                write_return_value,
        )

    @_UNIFFI_CALLBACK_INTERFACE_LOGGER_METHOD2
    def warn(
            uniffi_handle,
            msg,
            uniffi_out_return,
            uniffi_call_status_ptr,
        ):
        uniffi_obj = _UniffiConverterTypeLogger._handle_map.get(uniffi_handle)
        def make_call():
            args = (_UniffiConverterString.lift(msg), )
            method = uniffi_obj.warn
            return method(*args)

        
        write_return_value = lambda v: None
        _uniffi_trait_interface_call(
                uniffi_call_status_ptr.contents,
                make_call,
                write_return_value,
        )

    @_UNIFFI_CALLBACK_INTERFACE_LOGGER_METHOD3
    def error(
            uniffi_handle,
            msg,
            uniffi_out_return,
            uniffi_call_status_ptr,
        ):
        uniffi_obj = _UniffiConverterTypeLogger._handle_map.get(uniffi_handle)
        def make_call():
            args = (_UniffiConverterString.lift(msg), )
            method = uniffi_obj.error
            return method(*args)

        
        write_return_value = lambda v: None
        _uniffi_trait_interface_call(
                uniffi_call_status_ptr.contents,
                make_call,
                write_return_value,
        )

    @_UNIFFI_CALLBACK_INTERFACE_FREE
    def _uniffi_free(uniffi_handle):
        _UniffiConverterTypeLogger._handle_map.remove(uniffi_handle)

    # Generate the FFI VTable.  This has a field for each callback interface method.
    _uniffi_vtable = _UniffiVTableCallbackInterfaceLogger(
        debug,
        info,
        warn,
        error,
        _uniffi_free
    )
    # Send Rust a pointer to the VTable.  Note: this means we need to keep the struct alive forever,
    # or else bad things will happen when Rust tries to access it.
    _UniffiLib.uniffi_indexd_fn_init_callback_vtable_logger(ctypes.byref(_uniffi_vtable))



class _UniffiConverterTypeLogger:
    _handle_map = _UniffiHandleMap()

    @staticmethod
    def lift(value: int):
        return LoggerImpl._make_instance_(value)

    @staticmethod
    def check_lower(value: Logger):
        pass

    @staticmethod
    def lower(value: LoggerProtocol):
        return _UniffiConverterTypeLogger._handle_map.insert(value)

    @classmethod
    def read(cls, buf: _UniffiRustBuffer):
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: LoggerProtocol, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))
class AppProtocol(typing.Protocol):
    def connect(self, ):
        raise NotImplementedError
    def upload(self, encryption_key: "bytes",data_shards: "int",parity_shards: "int"):
        raise NotImplementedError
# App is a Rust-only trait - it's a wrapper around a Rust implementation.
class App():
    _pointer: ctypes.c_void_p
    def __init__(self, url: "str",name: "str",app_seed: "bytes",description: "str"):
        _UniffiConverterString.check_lower(url)
        
        _UniffiConverterString.check_lower(name)
        
        _UniffiConverterBytes.check_lower(app_seed)
        
        _UniffiConverterString.check_lower(description)
        
        self._pointer = _uniffi_rust_call_with_error(_UniffiConverterTypeError,_UniffiLib.uniffi_indexd_fn_constructor_app_new,
        _UniffiConverterString.lower(url),
        _UniffiConverterString.lower(name),
        _UniffiConverterBytes.lower(app_seed),
        _UniffiConverterString.lower(description))

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_indexd_fn_free_app, pointer)

    def _uniffi_clone_pointer(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_indexd_fn_clone_app, self._pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst

    async def connect(self, ) -> None:

        return await _uniffi_rust_call_async(
            _UniffiLib.uniffi_indexd_fn_method_app_connect(
                self._uniffi_clone_pointer(), 
            ),
            _UniffiLib.ffi_indexd_rust_future_poll_void,
            _UniffiLib.ffi_indexd_rust_future_complete_void,
            _UniffiLib.ffi_indexd_rust_future_free_void,
            # lift function
            lambda val: None,
            
            
    # Error FFI converter
_UniffiConverterTypeError,

        )



    async def upload(self, encryption_key: "bytes",data_shards: "int",parity_shards: "int") -> "Upload":
        _UniffiConverterBytes.check_lower(encryption_key)
        
        _UniffiConverterUInt8.check_lower(data_shards)
        
        _UniffiConverterUInt8.check_lower(parity_shards)
        
        return await _uniffi_rust_call_async(
            _UniffiLib.uniffi_indexd_fn_method_app_upload(
                self._uniffi_clone_pointer(), 
        _UniffiConverterBytes.lower(encryption_key),
        _UniffiConverterUInt8.lower(data_shards),
        _UniffiConverterUInt8.lower(parity_shards)
            ),
            _UniffiLib.ffi_indexd_rust_future_poll_pointer,
            _UniffiLib.ffi_indexd_rust_future_complete_pointer,
            _UniffiLib.ffi_indexd_rust_future_free_pointer,
            # lift function
            _UniffiConverterTypeUpload.lift,
            
    # Error FFI converter
_UniffiConverterTypeError,

        )





class _UniffiConverterTypeApp:

    @staticmethod
    def lift(value: int):
        return App._make_instance_(value)

    @staticmethod
    def check_lower(value: App):
        if not isinstance(value, App):
            raise TypeError("Expected App instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: AppProtocol):
        if not isinstance(value, App):
            raise TypeError("Expected App instance, {} found".format(type(value).__name__))
        return value._uniffi_clone_pointer()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer):
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: AppProtocol, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))
class ChunkedBufferProtocol(typing.Protocol):
    def close(self, ):
        raise NotImplementedError
    def push_chunk(self, chunk: "bytes"):
        raise NotImplementedError
# ChunkedBuffer is a Rust-only trait - it's a wrapper around a Rust implementation.
class ChunkedBuffer():
    _pointer: ctypes.c_void_p
    def __init__(self, ):
        self._pointer = _uniffi_rust_call(_UniffiLib.uniffi_indexd_fn_constructor_chunkedbuffer_new,)

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_indexd_fn_free_chunkedbuffer, pointer)

    def _uniffi_clone_pointer(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_indexd_fn_clone_chunkedbuffer, self._pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst


    def close(self, ) -> None:
        _uniffi_rust_call_with_error(_UniffiConverterTypeError,_UniffiLib.uniffi_indexd_fn_method_chunkedbuffer_close,self._uniffi_clone_pointer(),)





    async def push_chunk(self, chunk: "bytes") -> None:

        _UniffiConverterBytes.check_lower(chunk)
        
        return await _uniffi_rust_call_async(
            _UniffiLib.uniffi_indexd_fn_method_chunkedbuffer_push_chunk(
                self._uniffi_clone_pointer(), 
        _UniffiConverterBytes.lower(chunk)
            ),
            _UniffiLib.ffi_indexd_rust_future_poll_void,
            _UniffiLib.ffi_indexd_rust_future_complete_void,
            _UniffiLib.ffi_indexd_rust_future_free_void,
            # lift function
            lambda val: None,
            
            
    # Error FFI converter
_UniffiConverterTypeError,

        )





class _UniffiConverterTypeChunkedBuffer:

    @staticmethod
    def lift(value: int):
        return ChunkedBuffer._make_instance_(value)

    @staticmethod
    def check_lower(value: ChunkedBuffer):
        if not isinstance(value, ChunkedBuffer):
            raise TypeError("Expected ChunkedBuffer instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: ChunkedBufferProtocol):
        if not isinstance(value, ChunkedBuffer):
            raise TypeError("Expected ChunkedBuffer instance, {} found".format(type(value).__name__))
        return value._uniffi_clone_pointer()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer):
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: ChunkedBufferProtocol, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))
class UploadProtocol(typing.Protocol):
    def finish(self, ):
        raise NotImplementedError
    def write(self, buf: "bytes"):
        raise NotImplementedError
# Upload is a Rust-only trait - it's a wrapper around a Rust implementation.
class Upload():
    _pointer: ctypes.c_void_p
    
    def __init__(self, *args, **kwargs):
        raise ValueError("This class has no default constructor")

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_indexd_fn_free_upload, pointer)

    def _uniffi_clone_pointer(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_indexd_fn_clone_upload, self._pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst

    async def finish(self, ) -> None:

        return await _uniffi_rust_call_async(
            _UniffiLib.uniffi_indexd_fn_method_upload_finish(
                self._uniffi_clone_pointer(), 
            ),
            _UniffiLib.ffi_indexd_rust_future_poll_void,
            _UniffiLib.ffi_indexd_rust_future_complete_void,
            _UniffiLib.ffi_indexd_rust_future_free_void,
            # lift function
            lambda val: None,
            
            
    # Error FFI converter
_UniffiConverterTypeError,

        )



    async def write(self, buf: "bytes") -> None:

        _UniffiConverterBytes.check_lower(buf)
        
        return await _uniffi_rust_call_async(
            _UniffiLib.uniffi_indexd_fn_method_upload_write(
                self._uniffi_clone_pointer(), 
        _UniffiConverterBytes.lower(buf)
            ),
            _UniffiLib.ffi_indexd_rust_future_poll_void,
            _UniffiLib.ffi_indexd_rust_future_complete_void,
            _UniffiLib.ffi_indexd_rust_future_free_void,
            # lift function
            lambda val: None,
            
            
    # Error FFI converter
_UniffiConverterTypeError,

        )





class _UniffiConverterTypeUpload:

    @staticmethod
    def lift(value: int):
        return Upload._make_instance_(value)

    @staticmethod
    def check_lower(value: Upload):
        if not isinstance(value, Upload):
            raise TypeError("Expected Upload instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: UploadProtocol):
        if not isinstance(value, Upload):
            raise TypeError("Expected Upload instance, {} found".format(type(value).__name__))
        return value._uniffi_clone_pointer()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer):
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: UploadProtocol, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))

# Async support# RustFuturePoll values
_UNIFFI_RUST_FUTURE_POLL_READY = 0
_UNIFFI_RUST_FUTURE_POLL_MAYBE_READY = 1

# Stores futures for _uniffi_continuation_callback
_UniffiContinuationHandleMap = _UniffiHandleMap()

_UNIFFI_GLOBAL_EVENT_LOOP = None

"""
Set the event loop to use for async functions

This is needed if some async functions run outside of the eventloop, for example:
    - A non-eventloop thread is spawned, maybe from `EventLoop.run_in_executor` or maybe from the
      Rust code spawning its own thread.
    - The Rust code calls an async callback method from a sync callback function, using something
      like `pollster` to block on the async call.

In this case, we need an event loop to run the Python async function, but there's no eventloop set
for the thread.  Use `uniffi_set_event_loop` to force an eventloop to be used in this case.
"""
def uniffi_set_event_loop(eventloop: asyncio.BaseEventLoop):
    global _UNIFFI_GLOBAL_EVENT_LOOP
    _UNIFFI_GLOBAL_EVENT_LOOP = eventloop

def _uniffi_get_event_loop():
    if _UNIFFI_GLOBAL_EVENT_LOOP is not None:
        return _UNIFFI_GLOBAL_EVENT_LOOP
    else:
        return asyncio.get_running_loop()

# Continuation callback for async functions
# lift the return value or error and resolve the future, causing the async function to resume.
@_UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK
def _uniffi_continuation_callback(future_ptr, poll_code):
    (eventloop, future) = _UniffiContinuationHandleMap.remove(future_ptr)
    eventloop.call_soon_threadsafe(_uniffi_set_future_result, future, poll_code)

def _uniffi_set_future_result(future, poll_code):
    if not future.cancelled():
        future.set_result(poll_code)

async def _uniffi_rust_call_async(rust_future, ffi_poll, ffi_complete, ffi_free, lift_func, error_ffi_converter):
    try:
        eventloop = _uniffi_get_event_loop()

        # Loop and poll until we see a _UNIFFI_RUST_FUTURE_POLL_READY value
        while True:
            future = eventloop.create_future()
            ffi_poll(
                rust_future,
                _uniffi_continuation_callback,
                _UniffiContinuationHandleMap.insert((eventloop, future)),
            )
            poll_code = await future
            if poll_code == _UNIFFI_RUST_FUTURE_POLL_READY:
                break

        return lift_func(
            _uniffi_rust_call_with_error(error_ffi_converter, ffi_complete, rust_future)
        )
    finally:
        ffi_free(rust_future)

def set_log_callback(callback: "Logger") -> None:
    _UniffiConverterTypeLogger.check_lower(callback)
    
    _uniffi_rust_call(_UniffiLib.uniffi_indexd_fn_func_set_log_callback,
        _UniffiConverterTypeLogger.lower(callback))


__all__ = [
    "InternalError",
    "BufferError",
    "Error",
    "set_log_callback",
    "App",
    "ChunkedBuffer",
    "Logger",
    "Upload",
]

