name: Release

on:
  pull_request:
    types: [closed]
    branches: [master]

permissions:
  contents: write


jobs:
  release:
    if: github.head_ref == 'release' && github.event.pull_request.merged == true
    runs-on: tenki-standard-autoscale
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Environment
        run: |
          rustup update stable
          cargo install knope
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_API_KEY }}
        run: |
          knope release
          cargo publish --workspace --registry crates-io